# Hermetic unit tests for the "editable config via mkOutOfStoreSymlink" migration.
#
# These import the ghostty and claude-code home modules as *plain functions*
# with a mocked `config`/`pkgs`, so they need only the Nix evaluator — no
# home-manager, no nix-darwin, no flake inputs, no network. That makes them
# runnable on Linux CI even though the real system config is darwin-only.
#
# The mock records every `config.lib.file.mkOutOfStoreSymlink` call by
# returning a tagged attrset `{ __outOfStoreSymlink = true; target = <path>; }`
# instead of a real derivation, so we can assert exactly what each file links to.
#
# Run:  nix eval --raw -f tests/symlink-migration.nix   (or: tests/run.sh)
let
  homeDir = "/home/gattest";
  flakeDir = "${homeDir}/.config/nix-config";

  mockConfig = {
    home.homeDirectory = homeDir;
    lib.file.mkOutOfStoreSymlink = path: {
      __outOfStoreSymlink = true;
      target = toString path;
    };
  };

  mockArgs = {
    config = mockConfig;
    pkgs = {
      stdenv.hostPlatform.isDarwin = true;
    };
    self = null;
    lib = { };
  };

  ghostty = import ../home/ghostty/default.nix mockArgs;
  claude = import ../home/claude-code/default.nix mockArgs;

  # Evaluate `e`, returning its value on success or `null` if it throws
  # (e.g. selecting `.target` on a plain path in the pre-migration state).
  try =
    e:
    let
      r = builtins.tryEval e;
    in
    if r.success then r.value else null;

  ## ---------------- ghostty ----------------
  gEntry = ghostty.xdg.configFile."ghostty/config";
  gTarget = try (gEntry.source.target or null);
  gExpected = "${flakeDir}/home/ghostty/config";
  gMutable = try (gEntry.mutable or false);

  ## ---------------- claude symlink ----------------
  claudeFiles = (claude.home or { }).file or { };
  cHas = claudeFiles ? ".claude/settings.json";
  cEntry = if cHas then claudeFiles.".claude/settings.json" else { };
  cTarget = if cHas then try (cEntry.source.target or null) else null;
  cExpected = "${flakeDir}/home/claude-code/settings.json";
  cForce = if cHas then try (cEntry.force or false) else false;
  ccode = claude.programs.claude-code or { };
  settingsRemoved = !(ccode ? settings);
  # MCP servers moved to the live-editable mcp.json (see home/claude-code);
  # the store-baked mcpServers option must now stay UNSET.
  mcpUnset = !(ccode ? mcpServers);

  ## ---------------- settings.json content ----------------
  settingsPath = ../home/claude-code/settings.json;
  sjson =
    if builtins.pathExists settingsPath then
      try (builtins.fromJSON (builtins.readFile settingsPath))
    else
      null;
  sjsonOk = sjson != null;
  # Each content check is guarded by `sjsonOk` so that a missing / invalid
  # settings.json produces clean per-check FAILs rather than aborting eval
  # (`&&` short-circuits, so `sjson` is only inspected once we know it parsed).
  themeOk = sjsonOk && (try (sjson.theme == "dark") == true);
  coauthorOk = sjsonOk && (try (sjson.includeCoAuthoredBy == false) == true);
  modeOk = sjsonOk && (try (sjson.permissions.defaultMode == "acceptEdits") == true);
  hooksOk =
    sjsonOk
    && (
      try (builtins.isList sjson.hooks.PostToolUse && builtins.length sjson.hooks.PostToolUse >= 1)
      == true
    );
  allowOk = sjsonOk && (try (builtins.elem "Edit" sjson.permissions.allow) == true);
  denyOk = sjsonOk && (try (builtins.elem "Read(./secrets/**)" sjson.permissions.deny) == true);
  statusOk = sjsonOk && (try (sjson.statusLine.command == "bunx ccstatusline@latest") == true);
  # settings.json is symlinked into the git repo, so it must never carry the
  # MCP blocks (which hold token placeholders / secrets).
  noSecretsOk = sjsonOk && (try (!(sjson ? mcpServers)) == true);

  checks = [
    {
      name = "ghostty: ~/.config/ghostty/config is an out-of-store symlink to the repo";
      ok = gTarget == gExpected;
      detail = "got=${toString gTarget} expected=${gExpected}";
    }
    {
      name = "ghostty: config is no longer a 'mutable' copy (edits would be clobbered)";
      ok = gMutable == false;
      detail = "mutable=${toString gMutable}";
    }
    {
      name = "claude: ~/.claude/settings.json is managed via home.file";
      ok = cHas;
      detail = "present=${toString cHas}";
    }
    {
      name = "claude: settings.json symlink points at the repo file";
      ok = cTarget == cExpected;
      detail = "got=${toString cTarget} expected=${cExpected}";
    }
    {
      name = "claude: symlink uses force=true (overwrites the tool-written file)";
      ok = cForce == true;
      detail = "force=${toString cForce}";
    }
    {
      name = "claude: 'settings' no longer generated by programs.claude-code";
      ok = settingsRemoved;
      detail = "removed=${toString settingsRemoved}";
    }
    {
      name = "claude: mcpServers option unset (servers live in editable mcp.json)";
      ok = mcpUnset;
      detail = "mcpServers=${toString mcpUnset}";
    }
    {
      name = "settings.json: parses as valid JSON";
      ok = sjsonOk;
      detail = "parsed=${toString sjsonOk}";
    }
    {
      name = "settings.json: theme == dark";
      ok = themeOk == true;
      detail = "";
    }
    {
      name = "settings.json: includeCoAuthoredBy == false";
      ok = coauthorOk == true;
      detail = "";
    }
    {
      name = "settings.json: permissions.defaultMode == acceptEdits";
      ok = modeOk == true;
      detail = "";
    }
    {
      name = "settings.json: PostToolUse hooks preserved";
      ok = hooksOk == true;
      detail = "";
    }
    {
      name = "settings.json: permissions.allow preserved";
      ok = allowOk == true;
      detail = "";
    }
    {
      name = "settings.json: permissions.deny preserved";
      ok = denyOk == true;
      detail = "";
    }
    {
      name = "settings.json: statusLine preserved";
      ok = statusOk == true;
      detail = "";
    }
    {
      name = "settings.json: carries no MCP blocks / secrets";
      ok = noSecretsOk == true;
      detail = "";
    }
  ];

  fmt =
    c:
    "  [${if c.ok then "PASS" else "FAIL"}] ${c.name}"
    + (if c.ok || c.detail == "" then "" else "\n         ${c.detail}");
  lines = builtins.concatStringsSep "\n" (map fmt checks);
  passed = builtins.length (builtins.filter (c: c.ok) checks);
  total = builtins.length checks;
in
lines
+ "\n\n${toString passed}/${toString total} passed"
+ (if passed == total then "\nRESULT: ALL PASS" else "\nRESULT: SOME FAIL")
