{
  config,
  lib,
  ...
}:
let
  # kinda ugly, maybe fix later
  flakeDir = "${config.home.homeDirectory}/.config/nix-config";
in
{
  programs.starship = {
    enable = true;
    enableBashIntegration = true;
    enableZshIntegration = true;
    enableFishIntegration = true;
    enableNushellIntegration = true;
    # Settings are no longer generated by Nix. The full attrset is preserved
    # (unimported) in ./settings.legacy.nix for reference / switch-back.
  };

  # Live-editable: symlink ~/.config/starship.toml straight to the repo file
  # (mkOutOfStoreSymlink) so tweaks apply instantly with no rebuild and flow
  # back to git. mkForce overrides the file the HM starship module would write
  # from `settings` (kept enable=true so the package + shell integrations stay).
  xdg.configFile."starship.toml" = lib.mkForce {
    source = config.lib.file.mkOutOfStoreSymlink "${flakeDir}/home/starship/starship.toml";
  };
}
